// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using VOM_HIVE.API.Data;

#nullable disable

namespace VOM_HIVE.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240912231203_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sp2.Models.CampaignModel", b =>
                {
                    b.Property<int>("id_campaign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_campaign");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_campaign"));

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("details");

                    b.Property<DateTime>("dt_register")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_register");

                    b.Property<int>("id_company")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_company");

                    b.Property<int>("id_product")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_product");

                    b.Property<string>("nm_campaign")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_campaing");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status");

                    b.Property<string>("target")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("target");

                    b.HasKey("id_campaign");

                    b.HasIndex("id_company");

                    b.HasIndex("id_product");

                    b.ToTable("Campaign");
                });

            modelBuilder.Entity("Sp2.Models.CompanyModel", b =>
                {
                    b.Property<int>("id_company")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_company");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_company"));

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("dt_register")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_register");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("email");

                    b.Property<string>("nm_company")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_company");

                    b.HasKey("id_company");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Sp2.Models.ProductModel", b =>
                {
                    b.Property<int>("id_product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_product");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_product"));

                    b.Property<string>("category_product")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("category_product");

                    b.Property<string>("nm_product")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_product");

                    b.HasKey("id_product");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Sp2.Models.ProfileuserModel", b =>
                {
                    b.Property<int>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_user");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_user"));

                    b.Property<DateTime>("dt_register")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_user");

                    b.Property<int>("id_company")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nm_user")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_user");

                    b.Property<string>("pass_user")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("pass_user");

                    b.Property<string>("permission_user")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("permission_user");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status_user");

                    b.HasKey("id_user");

                    b.HasIndex("id_company");

                    b.ToTable("Profile_user");
                });

            modelBuilder.Entity("Sp2.Models.CampaignModel", b =>
                {
                    b.HasOne("Sp2.Models.CompanyModel", "Company")
                        .WithMany("Campaigns")
                        .HasForeignKey("id_company")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sp2.Models.ProductModel", "Product")
                        .WithMany("Campaigns")
                        .HasForeignKey("id_product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sp2.Models.ProfileuserModel", b =>
                {
                    b.HasOne("Sp2.Models.CompanyModel", "Company")
                        .WithMany("Profile_users")
                        .HasForeignKey("id_company")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Sp2.Models.CompanyModel", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Profile_users");
                });

            modelBuilder.Entity("Sp2.Models.ProductModel", b =>
                {
                    b.Navigation("Campaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
